# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81f5276503fc2edc8e69be0b570fe609b1f5a1797fb455c9f80a3014dc0fcfe8bde440c524ec2c6d9e7d0d34cfdbcbd1c5fb3f9a5906b596b66415dc4a54d314

test:
  secret_key_base: c363dd27ce28c104dea7e35734d8255b34c2bfa791393e5db6830227d8f105218e9a4885f77221ef3fbc3fd523cbf2535e038b1d9323ce96d3b948a3d040f8ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
